### PR TITLE
Math Magicians : Full website

### PR DESCRIPTION
**Pull request by ohyajk**
I added three pages with components in React Math Magicians project with tailwind CSS.

The three pages include:-

👉 Home Page
👉 Calculator Page (Calculator Component Imported here)
👉 Quote Page

Additionally, I added a Navbar with working links to each page using SPA routing with React Router v6.
🪄🪄🪄🪄

### CODE REVIEW

**Review by Ghiftee — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️♻️
Hello @ohyajk  👋🏽 

Good job working on the project so far! 
To highlight 👍🏽 
✔️ Your app matches the given wireframe
✔️ No linter errors
✔️ Your app works as expected

However, there are some issues that you need to work on to go to the next project but you are almost there!



## Required Changes ♻️
- [x] Kindly remove the Microverse logo and ```Microverse README template```  writing from your README and replace them with your logo if you have one. This would make your README more personalized.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by ohyajk** [comment]
@Ghiftee Thank you for your helpful review. I have removed the Microverse logo and writing from the readme but I have a question that I would like you to help me with. Can I add my own logo in place of the Microverse logo? Please let me know so I can proceed to the next project with the correct format. Once again I want to extend my regards for your time.

**Review by TedLivist — APPROVED** [review]
## STATUS: APPROVED ✔️ ✔️

Hi @ohyajk,

✔️ Good documentation

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ghiftee** [comment]
Hi @ohyajk  I apologize for the late reply. Yes, you can add your own logo if you have one. Since you already merged this project, you can do so in the next one

**Pull request merged**
