### PR TITLE
Math Magicians : Setup Project

### PR DESCRIPTION
**Pull request by ohyajk**
I added Create React App with Linters & Tailwind CSS.

### CODE REVIEW

**Review by Davidosky007 — COMMENTED** [review]
Hi @ohyajk 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't follow the Gitflow pattern, Kindly create a pull request to compare your feature branch with the development branch and submit the link to that pull request via your Dashboard. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ohyajk** [comment]
Thank you @Davidosky007 for your review. I have added the dev branch and made it default. I also updated the pull request to merge into dev instead of main. Again I want to extend my gratitude for your valuable insight about my project.❤️

**Review by levy002 — APPROVED** [review]
## Hello @ohyajk 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ohyajk** [comment]
Thank you @levy002  for your helpful review.

**Pull request merged**
