### PR TITLE
Math Magicians : Refactor with Hooks

### PR DESCRIPTION
**Pull request by ohyajk**
I added React functional components with useState and other hooks to make Calculator functional.

### CODE REVIEW

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @ohyajk,

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Linter passed ✔️ 
- Functional components ✔️ 

## Required Changes ♻️
_Check the comments under the review._
- [x] Your MIT link in the readme is broken, kindly fix it.
- [ ]  I would advise you to make a descriptive PR. A descriptive PR includes a descriptive title telling what changes are inside and a summary describing introduced changes in more detail.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ohyajk** [comment]
Hi, @Olamarx I would advise you to add your comments as optional because the required changes are not part of the current review. Hope you will correct your mistake next time.

**Comment by medaminedev66** [comment]
Hello @ohyajk 👋,

_This is an additional review as a result of the second opinion request._

@ohyajk Please keep in mind that we should submit the readme file without any broken links. Your README is the entry point of your users and having it well-written without any broken links gives a good first impression and maximizes the potential of your product to your users. Therefore, you should fix all the broken links in your readme file (MIT link, demo link ...) so it's professional.

Regarding the PR, I think it is descriptive, therefore you can disregard the proposed change.

Keep rocking 🚀!

**Review by jerryowusu — APPROVED** [review]
Hi @ohyajk  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

yeasss


## Highlights
All linters are passing :heavy_check_mark: 
Great effort so far :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
